### PR TITLE
Remove job listing for remoteStorage connect UI

### PR DESCRIPTION
**Pull request by skddc**
Successfully found a person (currently working on it) via this job board. Thanks, OSD! :)

### CODE REVIEW

**Comment by jancborchardt** [comment]
greatsuccess

**Comment by bnvk** [comment]
Yay success :grin: however, I wonder if we should maybe not "delete" a whole item, but rather switch the state of it to "completed" or something? That way keeps a record of successes... @jancborchardt @skddc

**Comment by jancborchardt** [comment]
Yeah, we could move them to a "jobs/completed" subfolder?

@simonv3 that way they won't be grabbed by jekyll for the list, will they?

**Comment by simonv3** [comment]
The way it's set up at the moment is that it'll just look for anything that could be a post. We could wrap an if statement around the loop to look for a `status` of the post.

**Comment by simonv3** [comment]
We could also move things into one folder so that it doesn't post everything. I just set it up that way cause I was hesitant to restructure the way everything was.

**Comment by jancborchardt** [comment]
(I mentioned the way of doing it via subfolder so that completed posts don't litter up the main "jobs" folder.)

**Pull request merged**
