### PR TITLE
Feature/move to jekyll

### PR DESCRIPTION
**Pull request by simonv3**
Lets make this an actual website, not just a github page.

This uses jekyll, and looks for pages with layout 'jobs', and puts those on our front page. We can move them to _posts if we want, but I don't think it's necessary.

### CODE REVIEW

**Comment by bnvk** [comment]
@simonv3 great stuff mang. Thanks for helping out ;)

**Comment by skddc** [comment]
its-happening

**Comment by jancborchardt** [comment]
Awesome stuff! :)

(Remember branch deletion after merging, homies. ;)

**Comment by jancborchardt** [comment]
Btw – should we maybe just remove master now, set gh-pages as default branch and work on that? Otherwise we just have duplication.

**Comment by simonv3** [comment]
Works for me

**Comment by jancborchardt** [comment]
Done

**Comment by jancborchardt** [comment]
You need to update your local clones now though @simonv3 @bnvk – best just delete and re-clone.

**Comment by pfefferle** [comment]
what about also deleting the master branch: http://oli.jp/2011/github-pages-workflow/#deleting-master

**Comment by pfefferle** [comment]
Oops... Already done... Never mind :)

**Comment by jancborchardt** [comment]
Yup. :) These days it’s even super-easy to delete branches through the web interface here.

**Pull request merged**
